apis:
  tracebud:
    root: docs/openapi/tracebud-v1-draft.yaml

extends:
  - recommended

rules:
  struct: error
  no-unresolved-refs: error
  operation-operationId: error
  operation-4xx-response: error
  tag-description: warn
  info-license: warn
  no-server-example.com: warn
