apis:
  tracebud:
    root: docs/openapi/tracebud-v1-draft.yaml
    x-openapi-ts:
      output: apps/dashboard-product/lib/generated/openapi-v1.d.ts
  tracebud-offline:
    root: docs/openapi/tracebud-v1-draft.yaml
    x-openapi-ts:
      output: apps/offline-product/features/api/generated/openapi-v1.d.ts

extends:
  - recommended

rules:
  struct: error
  no-unresolved-refs: error
  operation-operationId: error
  operation-4xx-response: error
  tag-description: warn
  info-license: warn
  no-server-example.com: warn
