import { StyleSheet } from 'react-native';

import { Brand } from '@/constants/theme';
import type { AppColors } from '@/features/theme/useThemedStyles';
import { scaleText } from '@/features/demo/storeUiScale';

export function createWalkPerimeterScreenStyles(c: AppColors) {
  return StyleSheet.create({
  screen: {
    flex: 1,
  },
  bodyFlex: {
    flex: 1,
  },
  walkPinnedFooter: {
    paddingHorizontal: 16,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: c.border,
    backgroundColor: c.backgroundCard,
    zIndex: 10,
    elevation: 10,
  },
  walkPinnedFooterExpanded: {
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 12,
    zIndex: 2,
  },
  header: {
    paddingHorizontal: 16,
    paddingBottom: 6,
  },
  headerTopRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    paddingTop: 4,
  },
  headerRowCompact: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    paddingTop: 6,
    paddingBottom: 4,
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    minWidth: 78,
  },
  headerTitleCompact: {
    color: '#FFFFFF',
    fontSize: scaleText(18),
    lineHeight: scaleText(24),
    flexGrow: 1,
    flexShrink: 1,
    textAlign: 'center',
    marginHorizontal: 4,
  },
  statusPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 9999,
    backgroundColor: 'rgba(242, 201, 76, 0.22)',
  },
  statusPillText: {
    color: c.surfaceWarningBorder,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
  },
  langPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 9999,
    backgroundColor: 'rgba(255,255,255,0.14)',
    minWidth: 54,
    justifyContent: 'center',
  },
  headerTrailing: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  langDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
    backgroundColor: '#9FE6C9',
  },
  container: {
    padding: 16,
    paddingBottom: 32,
    gap: 12,
  },
  containerLanding: {
    paddingTop: 10,
    paddingBottom: 10,
    gap: 10,
  },
  card: {
    marginTop: 2,
  },
  captureFlowCard: {
    borderWidth: 0,
    borderColor: 'transparent',
    paddingTop: 0,
    backgroundColor: 'transparent',
    borderRadius: 0,
    marginTop: 0,
  },
  instructionsRow: {
    alignItems: 'flex-end',
    marginBottom: -2,
  },
  instructionsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: c.chipBackgroundActive,
    borderWidth: 1,
    borderColor: c.surfaceAccentBorder,
  },
  instructionsButtonText: {
    color: c.link,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '600',
  },
  captureMethodsSection: {
    marginTop: 8,
    paddingHorizontal: 2,
  },
  captureMethodsIntro: {
    fontSize: scaleText(18),
    lineHeight: scaleText(28),
    color: c.textSecondary,
    marginBottom: 12,
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  buttonRow: {
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
  },
  buttonCell: {
    flex: 1,
  },
  list: {
    marginTop: 12,
  },
  mapContainer: {
    marginTop: 12,
    height: 250,
    borderRadius: 12,
    overflow: 'hidden',
  },
  map: {
    flex: 1,
  },
  rowCard: {
    padding: 12,
  },
  rowHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 12,
  },
  statChip: {
    flexBasis: '48%',
    flexGrow: 1,
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: 'rgba(56,161,105,0.10)',
  },
  statLabel: {
    opacity: 0.9,
    color: c.linkStrong,
  },
  statValue: {
    marginTop: 2,
    color: c.linkStrong,
  },
  gpsWarning: {
    marginTop: 12,
    padding: 12,
    borderRadius: 14,
    backgroundColor: 'rgba(221,107,32,0.10)',
    borderColor: 'rgba(221,107,32,0.25)',
  },
  gpsSignalCard: {
    borderRadius: 18,
    borderColor: c.surfaceAccentBorder,
    backgroundColor: c.surfaceAccent,
    paddingVertical: 10,
  },
  gpsSignalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  gpsSignalBadge: {
    backgroundColor: '#9FE6C9',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 5,
  },
  gpsSignalBadgeText: {
    color: c.link,
    fontWeight: '700',
  },
  gpsSignalMetaRow: {
    marginTop: 6,
    flexDirection: 'row',
    gap: 12,
  },
  gpsSignalMetaCell: {
    flex: 1,
  },
  gpsMetaLabel: {
    fontSize: 12,
    lineHeight: 16,
  },
  declarationsIntroCard: {
    borderRadius: 20,
    borderColor: c.surfaceActionBorder,
    backgroundColor: c.surfaceAction,
    marginTop: 2,
  },
  registrationIntroCard: {
    borderRadius: 20,
    borderColor: c.surfaceAccentBorder,
    backgroundColor: c.surfaceAccent,
    marginTop: 2,
  },
  declarationsIntroRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  declarationsIntroTitle: {
    color: c.textWarning,
  },
  declarationsIntroBody: {
    marginTop: 4,
    color: c.textWarningStrong,
    fontSize: 13,
    lineHeight: 20,
  },
  declarationItemCard: {
    borderWidth: 1,
    borderColor: c.border,
    backgroundColor: c.backgroundCard,
    borderRadius: 18,
    paddingVertical: 12,
    paddingHorizontal: 12,
    marginTop: 8,
  },
  declarationItemRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  declarationItemContent: {
    flex: 1,
  },
  declarationItemBody: {
    marginTop: 2,
    color: c.textMuted,
    fontSize: 13,
    lineHeight: 20,
  },
  declarationNoteCard: {
    borderWidth: 1,
    borderColor: c.border,
    backgroundColor: c.backgroundSecondary,
    borderRadius: 16,
    marginTop: 8,
  },
  declarationNoteText: {
    color: c.textMuted,
  },
  photoGrid: {
    marginTop: 10,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  photoSlot: {
    width: '48.5%',
    minHeight: 156,
    borderRadius: 18,
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: c.border,
    backgroundColor: c.backgroundSecondary,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    overflow: 'hidden',
    position: 'relative',
  },
  photoSlotCaptured: {
    borderColor: '#10B981',
    backgroundColor: c.avatarBackground,
  },
  photoPreview: {
    ...StyleSheet.absoluteFillObject,
    width: undefined,
    height: undefined,
  },
  photoCapturedOverlay: {
    position: 'absolute',
    top: 8,
    right: 8,
    backgroundColor: '#FFFFFFE8',
    borderRadius: 999,
    padding: 2,
  },
  photoSlotTitle: {
    color: c.textMuted,
  },
  photoSlotTitleCaptured: {
    color: c.link,
  },
  photoSlotHint: {
    color: c.textMuted,
  },
  photoActionRow: {
    marginTop: 10,
    flexDirection: 'row',
    gap: 8,
  },
  completionLandHint: {
    textAlign: 'center',
    color: c.textMuted,
    marginBottom: 4,
  },
  completionHero: {
    alignItems: 'center',
    marginTop: 8,
  },
  completionHeroCompact: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 4,
  },
  completionRequiredHeader: {
    gap: 10,
    marginBottom: 8,
  },
  completionBoundarySaved: {
    color: c.link,
    marginTop: 2,
  },
  completionRequiredBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    padding: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: c.surfaceWarningBorder,
    backgroundColor: c.surfaceWarning,
  },
  completionRequiredTitle: {
    color: c.textWarning,
  },
  completionRequiredBody: {
    marginTop: 4,
    color: c.textWarningStrong,
    lineHeight: 18,
  },
  completionSkipLink: {
    marginTop: 14,
    alignItems: 'center',
    paddingVertical: 8,
  },
  completionSkipLinkText: {
    color: c.textMuted,
    textAlign: 'center',
    lineHeight: 18,
  },
  completionIconWrap: {
    width: 122,
    height: 122,
    borderRadius: 61,
    backgroundColor: c.avatarBackground,
    alignItems: 'center',
    justifyContent: 'center',
  },
  completionTitle: {
    marginTop: 16,
    color: c.text,
  },
  completionBody: {
    marginTop: 8,
    textAlign: 'center',
    color: c.textMuted,
    maxWidth: 320,
    fontSize: 15,
    lineHeight: 26 / 1.35,
  },
  completionPlotName: {
    marginTop: 0,
    color: c.linkStrong,
    textAlign: 'left',
  },
  completionSecondaryLink: {
    marginTop: 14,
    alignItems: 'center',
    paddingVertical: 8,
  },
  completionSecondaryLinkText: {
    color: c.link,
    fontSize: 15,
  },
  completionFinishLater: {
    marginTop: 12,
    color: c.textMuted,
    lineHeight: 20,
  },
  completionChipRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 10,
  },
  completionChip: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: c.surfaceAccentBorder,
    backgroundColor: c.surfaceAccent,
  },
  completionChipText: {
    color: c.link,
    fontWeight: '600',
  },
  completionStatusCard: {
    marginTop: 14,
    borderRadius: 18,
    borderColor: c.border,
    backgroundColor: c.backgroundCard,
    padding: 14,
    gap: 8,
  },
  completionStatusHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  completionStatusTitle: {
    flex: 1,
    fontSize: 15,
    lineHeight: 22,
    color: c.text,
  },
  pendingReviewPill: {
    backgroundColor: c.surfaceWarning,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 5,
    marginLeft: 4,
    flexShrink: 0,
  },
  pendingReviewText: {
    color: c.textWarningStrong,
    fontWeight: '700',
    fontSize: 12,
    lineHeight: 16,
  },
  completionListRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  completionDot: {
    width: 10,
    height: 10,
    borderRadius: 999,
  },
  walkMapPanel: {
    marginTop: 8,
    borderRadius: 18,
    overflow: 'hidden',
    backgroundColor: c.storageTrack,
    minHeight: 248,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  walkMap: {
    width: '100%',
    height: 206,
  },
  walkMapPlaceholder: {
    width: '100%',
    height: 206,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: c.storageTrack,
  },
  coordChip: {
    position: 'absolute',
    bottom: 14,
    alignSelf: 'center',
    backgroundColor: c.backgroundCard,
    borderWidth: 1,
    borderColor: c.borderStrong,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 6,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.28,
    shadowRadius: 4,
    elevation: 5,
  },
  walkStatsRow: {
    marginTop: 8,
    flexDirection: 'row',
    gap: 8,
  },
  walkStatCard: {
    flex: 1,
    borderWidth: 1,
    borderColor: c.border,
    borderRadius: 12,
    backgroundColor: c.backgroundCard,
    minHeight: 86,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 1,
  },
  walkStatCardCompact: {
    minHeight: 72,
  },
  walkGuideStrip: {
    gap: 8,
    marginBottom: 8,
  },
  walkGuideHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  walkGuideTitle: {
    color: c.linkStrong,
    flex: 1,
  },
  walkGuideRecordingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: c.surfaceAccent,
    borderWidth: 1,
    borderColor: c.surfaceAccentBorder,
  },
  walkGuideRecordingText: {
    flex: 1,
    color: c.linkStrong,
    lineHeight: 20,
  },
  walkGuideWaitRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: c.surfaceWarning,
    borderWidth: 1,
    borderColor: c.surfaceWarningBorder,
  },
  walkGuideWaitText: {
    flex: 1,
    color: c.textWarning,
    lineHeight: 18,
  },
  walkGuideInlineTip: {
    textAlign: 'center',
    color: c.textSecondary,
    lineHeight: 20,
    paddingHorizontal: 4,
  },
  walkMapTopTip: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: c.backgroundElevated,
    borderBottomWidth: 1,
    borderBottomColor: c.borderStrong,
  },
  walkMapTopTipText: {
    color: c.linkStrong,
    textAlign: 'center',
    fontWeight: '600',
    lineHeight: 18,
  },
  walkInstructionRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  walkInstructionText: {
    flex: 1,
    color: c.text,
    lineHeight: 18,
  },
  alternateCapturePanel: {
    marginTop: 2,
    gap: 8,
    borderWidth: 1,
    borderColor: c.border,
    borderRadius: 14,
    padding: 12,
    backgroundColor: c.backgroundSecondary,
  },
  alternateCaptureIntro: {
    color: c.textMuted,
    marginBottom: 4,
  },
  alternateCaptureRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    paddingVertical: 8,
  },
  alternateCaptureTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 6,
  },
  alternateCaptureFallback: {
    color: c.textMuted,
    fontSize: 11,
  },
  walkStatValue: {
    color: c.text,
    fontSize: 17,
    lineHeight: 20,
  },
  walkStatLabel: {
    color: c.textMuted,
    fontSize: 11,
    lineHeight: 16,
  },
  averagingCard: {
    marginTop: 10,
    borderRadius: 18,
    borderColor: c.border,
    backgroundColor: c.backgroundCard,
  },
  averagingHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  averagingTitle: {
    color: c.textSecondary,
    fontSize: 16 / 1.05,
    lineHeight: 28,
  },
  averagingPercent: {
    color: c.link,
    fontSize: 18 / 1.1,
    lineHeight: 28 / 1.1,
  },
  averagingTrack: {
    height: 14,
    borderRadius: 999,
    backgroundColor: c.storageTrack,
    overflow: 'hidden',
    marginTop: 8,
  },
  averagingFill: {
    height: 14,
    borderRadius: 999,
    backgroundColor: '#0CB67A',
  },
  averagingBody: {
    marginTop: 10,
    color: c.textMuted,
    fontSize: 13,
    lineHeight: 20,
  },
  drawInfoCard: {
    borderRadius: 16,
    backgroundColor: c.backgroundSecondary,
    borderColor: c.border,
    borderWidth: 1,
    padding: 12,
    marginBottom: 4,
    gap: 6,
  },
  drawInfoText: {
    color: c.text,
    lineHeight: 20,
  },
  manualTraceOfflineHint: {
    marginTop: 8,
    color: c.linkStrong,
    lineHeight: 18,
  },
  cornerModeIntro: {
    color: c.textSecondary,
    lineHeight: 18,
  },
  cornerCompactStats: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 10,
  },
  cornerHintCard: {
    borderRadius: 16,
    backgroundColor: c.backgroundSecondary,
    borderColor: c.border,
  },
  cornerHoldLabel: {
    textAlign: 'center',
    color: c.textMuted,
  },
  cornerCountLabel: {
    textAlign: 'center',
    color: c.link,
    fontWeight: '600',
  },
  drawMapPanel: {
    marginTop: 12,
    borderRadius: 18,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: c.dashedBorder,
    borderStyle: 'dashed',
    backgroundColor: c.storageTrack,
    minHeight: 330,
    position: 'relative',
  },
  drawMap: {
    width: '100%',
    height: 330,
  },
  drawMapOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(189,209,200,0.84)',
  },
  drawChip: {
    position: 'absolute',
    left: 12,
    bottom: 12,
    backgroundColor: c.backgroundElevated,
    borderWidth: 1,
    borderColor: c.borderStrong,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  gpsInfoCard: {
    marginTop: 12,
    padding: 12,
    borderRadius: 14,
    backgroundColor: 'rgba(37,99,235,0.06)',
    borderColor: 'rgba(37,99,235,0.18)',
  },
  plotRegistrationCard: {
    marginTop: 8,
    borderColor: c.surfaceAccentBorder,
    backgroundColor: c.surfaceAccent,
    borderRadius: 16,
    padding: 12,
  },
  plotLandingCombinedCard: {
    marginTop: 8,
    borderRadius: 18,
    padding: 18,
    gap: 4,
  },
  plotRegisterLandingHint: {
    color: c.textMuted,
    lineHeight: scaleText(20),
    marginBottom: 8,
  },
  plotLandingIntro: {
    color: c.textSecondary,
    fontSize: scaleText(14),
    lineHeight: scaleText(20),
  },
  plotLandingFarmerHint: {
    marginTop: 6,
    color: c.textMuted,
  },
  plotNameDuplicateHint: {
    marginTop: 6,
    color: c.error,
    lineHeight: scaleText(18),
  },
  plotNameDuplicateSuggestLink: {
    marginTop: 4,
    alignSelf: 'flex-start',
    paddingVertical: 4,
  },
  plotNameDuplicateSuggestLinkText: {
    color: c.linkStrong,
    lineHeight: scaleText(18),
  },
  plotLandingSizeLabel: {
    color: c.text,
    marginTop: 16,
  },
  plotLandingSizeHint: {
    marginTop: 8,
    color: c.textMuted,
    lineHeight: scaleText(18),
  },
  sizePillRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 10,
  },
  sizePill: {
    flex: 1,
    borderWidth: 1.5,
    borderColor: c.border,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 10,
    alignItems: 'center',
    backgroundColor: c.backgroundSecondary,
  },
  sizePillSelected: {
    borderColor: c.link,
    backgroundColor: c.chipBackgroundActive,
  },
  sizePillLabel: {
    color: c.text,
    fontSize: scaleText(15),
  },
  sizePillLabelSelected: {
    color: c.link,
  },
  gpsStrip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 14,
    backgroundColor: c.backgroundCard,
    borderWidth: 1,
    borderColor: c.border,
  },
  gpsStripDot: {
    width: 10,
    height: 10,
    borderRadius: 999,
  },
  gpsStripLabel: {
    flex: 1,
    color: c.text,
  },
  walkTipText: {
    textAlign: 'center',
    color: c.textSecondary,
    fontSize: scaleText(14),
    lineHeight: scaleText(20),
  },
  walkRecordingTip: {
    textAlign: 'center',
    color: c.link,
    fontSize: scaleText(15),
    lineHeight: scaleText(22),
    fontWeight: '600',
    marginTop: 4,
  },
  gpsWaitBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: c.surfaceWarning,
    borderWidth: 1,
    borderColor: c.surfaceWarningBorder,
  },
  gpsWaitBannerText: {
    flex: 1,
    color: c.textWarning,
    lineHeight: 18,
  },
  recordingMapBadge: {
    position: 'absolute',
    top: 12,
    right: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: '#FFFFFFE8',
  },
  recordingMapPulse: {
    position: 'absolute',
    left: 10,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: 'rgba(16, 185, 129, 0.35)',
  },
  recordingMapDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#10B981',
  },
  recordingMapLabel: {
    color: c.linkStrong,
    fontWeight: '700',
    fontSize: 12,
  },
  mapGpsPill: {
    position: 'absolute',
    top: 12,
    left: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: c.backgroundCard,
    borderWidth: 1,
    borderColor: c.borderStrong,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.28,
    shadowRadius: 4,
    elevation: 5,
  },
  mapGpsDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  cornerCountChip: {
    position: 'absolute',
    bottom: 12,
    left: 12,
    right: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: c.backgroundCard,
    borderWidth: 1,
    borderColor: c.borderStrong,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.28,
    shadowRadius: 4,
    elevation: 5,
  },
  cornerCountChipText: {
    color: c.text,
    fontWeight: '600',
    fontSize: 13,
    lineHeight: 18,
    textAlign: 'center',
  },
  mapInstructionBanner: {
    position: 'absolute',
    top: 48,
    left: 12,
    right: 12,
    backgroundColor: c.backgroundCard,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: c.borderStrong,
    paddingHorizontal: 12,
    paddingVertical: 10,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.28,
    shadowRadius: 4,
    elevation: 5,
  },
  mapInstructionBannerText: {
    color: c.text,
    fontWeight: '600',
    fontSize: 13,
    lineHeight: 18,
    textAlign: 'center',
  },
  mapGpsPillText: {
    color: c.text,
    fontWeight: '600',
    fontSize: 12,
  },
  walkCaptureHint: {
    textAlign: 'center',
    color: c.textSecondary,
    lineHeight: 18,
    paddingHorizontal: 4,
  },
  walkStepsRow: {
    flexDirection: 'row',
    gap: 6,
  },
  walkStepChip: {
    flex: 1,
    alignItems: 'center',
    gap: 4,
    paddingVertical: 8,
    paddingHorizontal: 4,
    borderRadius: 12,
    backgroundColor: c.backgroundCard,
    borderWidth: 1,
    borderColor: c.border,
  },
  walkStepNumber: {
    width: 22,
    height: 22,
    borderRadius: 999,
    backgroundColor: c.chipBackgroundActive,
    alignItems: 'center',
    justifyContent: 'center',
  },
  walkStepNumberText: {
    color: c.link,
    fontWeight: '700',
    fontSize: 11,
  },
  walkStepLabel: {
    color: c.textMuted,
    textAlign: 'center',
    fontSize: 10,
    lineHeight: 14,
  },
  averagingTrackWrap: {
    width: '100%',
    alignSelf: 'stretch',
    marginTop: 10,
  },
  averagingTrackCompact: {
    width: '100%',
    alignSelf: 'stretch',
    height: 6,
    borderRadius: 999,
    backgroundColor: c.border,
    overflow: 'hidden',
  },
  averagingFillCompact: {
    height: 6,
    borderRadius: 999,
    backgroundColor: '#0CB67A',
  },
  otherWaysLink: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    paddingVertical: 8,
  },
  otherWaysLinkText: {
    color: c.textMuted,
  },
  plotRegistrationRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  sizeGrid: {
    flexDirection: 'row',
    gap: 10,
  },
  sizeCard: {
    flex: 1,
    borderWidth: 1,
    borderColor: c.border,
    borderRadius: 14,
    padding: 12,
    minHeight: 112,
    backgroundColor: c.backgroundCard,
  },
  sizeCardSelected: {
    borderColor: c.link,
    backgroundColor: c.chipBackgroundActive,
  },
  contiguityCard: {
    marginTop: 2,
    borderColor: c.border,
    backgroundColor: c.backgroundSecondary,
    borderRadius: 16,
    padding: 14,
  },
  contiguityRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  continueButtonWrap: {
    marginTop: 4,
  },
  captureCard: {
    borderWidth: 1,
    borderColor: c.border,
    borderRadius: 24,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    backgroundColor: c.backgroundCard,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  captureCardSelected: {
    borderColor: c.link,
    backgroundColor: c.backgroundCard,
  },
  captureIconPillWalk: {
    width: 50,
    height: 50,
    borderRadius: 12,
    backgroundColor: c.surfaceAccent,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
  },
  captureIconPillDraw: {
    width: 50,
    height: 50,
    borderRadius: 12,
    backgroundColor: c.backgroundSecondary,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
  },
  captureIconPillCentroid: {
    width: 50,
    height: 50,
    borderRadius: 12,
    backgroundColor: c.backgroundSecondary,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
  },
  captureIconPillPin: {
    width: 50,
    height: 50,
    borderRadius: 12,
    backgroundColor: c.avatarBackground,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
  },
  captureTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'nowrap',
    gap: 8,
  },
  captureTitleText: {
    fontSize: scaleText(18),
    lineHeight: scaleText(24),
    color: c.text,
    flexGrow: 1,
    flexShrink: 1,
    minWidth: 108,
  },
  captureBodyText: {
    marginTop: 6,
    fontSize: scaleText(14),
    lineHeight: scaleText(20),
    color: c.textSecondary,
  },
  recommendedPill: {
    backgroundColor: c.chipBackgroundActive,
    borderRadius: 9999,
    paddingHorizontal: 8,
    paddingVertical: 4,
    alignSelf: 'flex-start',
    marginRight: 12,
    minWidth: 118,
    flexShrink: 0,
  },
  recommendedPillText: {
    color: c.link,
    fontWeight: '700',
    fontSize: scaleText(12),
  },
  fallbackPill: {
    backgroundColor: c.surfaceWarning,
    borderRadius: 9999,
    paddingHorizontal: 8,
    paddingVertical: 4,
    alignSelf: 'flex-start',
    marginRight: 12,
    minWidth: 0,
    flexShrink: 0,
  },
  fallbackPillText: {
    color: c.textWarningStrong,
    fontWeight: '700',
    fontSize: scaleText(12),
  },
  captureChevron: {
    marginLeft: 'auto',
  },
  commodityChip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 9999,
    backgroundColor: c.border,
    borderWidth: 1,
    borderColor: c.chipBorder,
  },
  commodityChipSelected: {
    backgroundColor: c.link,
    borderColor: c.link,
  },
});
}
