import { StyleSheet } from 'react-native';

import { Brand, Radius, Spacing } from '@/constants/theme';
import type { AppColors } from '@/features/theme/useThemedStyles';

export function createMultiPlotDeliveryWizardStyles(c: AppColors) {
  return StyleSheet.create({
  gap: { gap: 16 },
  gapSm: { gap: 10 },
  introCard: {
    borderRadius: 18,
    borderColor: c.surfaceAccentBorder,
    backgroundColor: c.surfaceAccent,
    padding: 14,
  },
  lineCard: { padding: 14, borderRadius: 16 },
  lineRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  plotCard: { padding: 14, borderRadius: 16 },
  plotDisabled: { opacity: 0.7 },
  plotSeasonText: { color: c.textMuted, marginTop: 2 },
  plotLocalBadge: { color: c.textWarningStrong, marginTop: 4 },
  weightPlotChip: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: c.surfaceAccent,
  },
  weightPlotChipText: { color: c.linkStrong, fontSize: 14 },
  weightCard: { borderRadius: 18, padding: 16, backgroundColor: c.backgroundCard },
  weightLabel: {
    color: c.text,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    fontSize: 11,
    marginBottom: 8,
  },
  weightInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: c.border,
    borderRadius: 14,
    backgroundColor: c.backgroundSecondary,
    paddingHorizontal: 14,
    paddingVertical: 10,
    gap: 8,
  },
  weightInput: {
    flex: 1,
    textAlign: 'right',
    fontSize: 28,
    fontWeight: '700',
    color: c.text,
    paddingVertical: 0,
  },
  weightUnit: { color: c.textMuted, fontSize: 16, minWidth: 24 },
  inlinePlotCard: { padding: 14, borderRadius: 16, gap: 10 },
  inlinePlotHeader: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  inlinePlotIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: c.surfaceAccent,
    alignItems: 'center',
    justifyContent: 'center',
  },
  inlinePlotText: { flex: 1, minWidth: 0 },
  inlineWeightRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: c.border,
    borderRadius: 14,
    backgroundColor: c.backgroundSecondary,
    paddingHorizontal: 14,
    paddingVertical: 8,
    gap: 8,
  },
  inlineWeightInput: {
    flex: 1,
    textAlign: 'right',
    fontSize: 22,
    fontWeight: '700',
    color: c.text,
    paddingVertical: 4,
  },
  disabledBtn: { backgroundColor: c.border },
  btnTextOnGreen: { color: c.backgroundCard },
  btnTextDisabled: { color: c.textSecondary },
  completeTitle: { textAlign: 'center', fontSize: 32, lineHeight: 38 },
  completeBody: { textAlign: 'center', color: c.textSecondary },
  resultCard: { padding: 14, borderRadius: 16, alignItems: 'center', gap: 8 },
  tripCard: { padding: 16, borderRadius: 16, alignItems: 'center', gap: 8, borderColor: c.surfaceAccentBorder, backgroundColor: c.surfaceAccent },
  tripTitle: { color: c.linkStrong, textAlign: 'center' },
  tripBody: { color: c.textSecondary, textAlign: 'center' },
  qrWrap: { alignItems: 'center', gap: 8, marginTop: 8 },
  voucherCode: { color: c.text },
  generatingText: { color: c.textMuted, textAlign: 'center' },
  errorText: { color: c.textWarningStrong },
});
}
