export const BILLING_BAND_UPGRADE_REQUIRED = 'BILLING_BAND_UPGRADE_REQUIRED' as const;
export const ENTERPRISE_SALES_REQUIRED = 'ENTERPRISE_SALES_REQUIRED' as const;

export type ContactAddBlockCode =
  | typeof BILLING_BAND_UPGRADE_REQUIRED
  | typeof ENTERPRISE_SALES_REQUIRED;
