import { ApiProperty } from '@nestjs/swagger';
import { IsString } from 'class-validator';

export class CreatePlotAssignmentDto {
  @ApiProperty({ description: 'Assignment identifier generated by client or orchestrator' })
  @IsString()
  assignmentId!: string;

  @ApiProperty({ description: 'Agent user UUID assigned to the plot' })
  @IsString()
  agentUserId!: string;
}
