import { StyleSheet } from 'react-native';

import type { AppColors } from '@/features/theme/useThemedStyles';

export function createPlotDetailScreenStyles(c: AppColors) {
  return StyleSheet.create({
  screen: { flex: 1 },
  header: { paddingHorizontal: 16, paddingBottom: 6 },
  headerTopRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    paddingTop: 4,
  },
  headerRowCompact: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingTop: 6,
    paddingBottom: 4,
  },
  backPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 9999,
    backgroundColor: 'rgba(255,255,255,0.16)',
  },
  langPillCompact: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 9999,
    backgroundColor: 'rgba(255,255,255,0.16)',
    minWidth: 54,
    justifyContent: 'center',
  },
  langDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
    backgroundColor: c.avatarBackground,
  },
  container: { padding: 16, paddingBottom: 32, gap: 12 },
  card: { marginTop: 2 },
  summaryMetaRow: {
    marginTop: 12,
    flexDirection: 'row',
    gap: 10,
  },
  summaryMetaCell: {
    flex: 1,
    borderWidth: 1,
    borderColor: c.border,
    backgroundColor: c.backgroundSecondary,
    borderRadius: 14,
    padding: 10,
    gap: 4,
  },
  statusChecklistCard: {
    borderRadius: 18,
    borderColor: c.border,
    backgroundColor: c.backgroundCard,
    padding: 14,
    gap: 0,
  },
  progressHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 12,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  progressTrack: {
    flex: 1,
    height: 8,
    borderRadius: 999,
    backgroundColor: c.border,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: c.link,
  },
  progressLabel: {
    color: c.linkStrong,
    fontSize: 13,
    minWidth: 88,
    textAlign: 'right',
  },
  statusChecklistTitle: {
    color: c.linkStrong,
    fontSize: 16,
  },
  statusChecklistSub: {
    marginTop: 4,
    color: c.textSecondary,
    lineHeight: 18,
  },
  statusChecklistRows: {
    marginTop: 12,
    gap: 10,
  },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: c.border,
    backgroundColor: c.backgroundSecondary,
  },
  statusRowOpen: {
    borderColor: c.surfaceWarningBorder,
    backgroundColor: c.surfaceAction,
  },
  statusRowPressed: {
    opacity: 0.92,
  },
  statusRowBody: {
    flex: 1,
    flexShrink: 1,
  },
  statusRowCaptionOpen: {
    marginTop: 4,
    color: c.textMuted,
    lineHeight: 18,
  },
  statusRowTap: {
    color: c.link,
    alignSelf: 'center',
    fontWeight: '600',
  },
  statusRemainingFooterHint: {
    marginTop: 10,
    color: c.textMuted,
    lineHeight: 18,
  },
  statusAllDoneWrap: {
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 8,
  },
  statusAllDoneText: {
    flex: 1,
    color: c.link,
    fontWeight: '600',
    lineHeight: 22,
  },
  checkCard: {
    borderRadius: 18,
    borderColor: c.surfaceAccentBorder,
    backgroundColor: c.surfaceAccent,
  },
  checkIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: c.surfaceAccent,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navCard: {
    borderWidth: 1,
    borderColor: c.border,
    borderRadius: 18,
    backgroundColor: c.backgroundCard,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  navCardSelected: {
    borderColor: c.link,
  },
  navIconWrapPhoto: {
    width: 52,
    height: 52,
    borderRadius: 14,
    backgroundColor: c.surfaceAction,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navIconWrapDocs: {
    width: 52,
    height: 52,
    borderRadius: 14,
    backgroundColor: c.backgroundSecondary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navIconWrapHarvest: {
    width: 52,
    height: 52,
    borderRadius: 14,
    backgroundColor: c.avatarBackground,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navIconWrapVoucher: {
    width: 52,
    height: 52,
    borderRadius: 14,
    backgroundColor: c.backgroundSecondary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  photoIntroCard: {
    borderRadius: 18,
    borderColor: c.surfaceAccentBorder,
    backgroundColor: c.surfaceAccent,
  },
  photoIntroText: {
    color: c.linkStrong,
  },
  photoVaultGrid: {
    marginTop: 10,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  photoVaultSlot: {
    width: '48.5%',
    minHeight: 210,
    borderRadius: 16,
    backgroundColor: c.storageTrack,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    overflow: 'hidden',
  },
  photoVaultImage: {
    ...StyleSheet.absoluteFillObject,
    width: undefined,
    height: undefined,
  },
  photoVaultTitle: {
    color: c.textMuted,
  },
  photoVaultDate: {
    color: c.textMuted,
  },
  docCard: {
    gap: 0,
  },
  docNextStepCard: {
    padding: 12,
    borderLeftWidth: 3,
    borderLeftColor: c.warning,
  },
  docAllSetCard: {
    padding: 12,
    borderLeftWidth: 3,
    borderLeftColor: c.link,
  },
  docLandEditToggle: {
    padding: 12,
  },
  docLandEditToggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  docLandEditToggleSub: {
    marginTop: 4,
    color: c.textMuted,
  },
  docLandCollapseHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 4,
    marginBottom: 4,
  },
  docLandCollapseLabel: {
    color: c.textMuted,
  },
  docNoteCard: {
    paddingVertical: 4,
  },
  docStatusCard: {
    padding: 12,
  },
  docRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  docIconWrapGreen: {
    width: 52,
    height: 52,
    borderRadius: 16,
    backgroundColor: c.surfaceAccent,
    alignItems: 'center',
    justifyContent: 'center',
  },
  docIconWrapBlue: {
    width: 52,
    height: 52,
    borderRadius: 16,
    backgroundColor: c.backgroundSecondary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  docVerifiedText: {
    color: c.link,
  },
  docPendingText: {
    color: c.textWarningStrong,
  },
  docCodeWrap: {
    marginTop: 14,
    borderRadius: 12,
    backgroundColor: c.storageTrack,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  docCodeText: {
    color: c.textSecondary,
  },
  docSubText: {
    marginTop: 10,
    color: c.textMuted,
  },
  uploadDocCta: {
    marginTop: 12,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: c.link,
    borderStyle: 'dashed',
    backgroundColor: c.surfaceAccent,
    minHeight: 86,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  uploadDocText: {
    color: c.link,
  },
  harvestSummaryCard: {
    borderRadius: 20,
    backgroundColor: c.backgroundSecondary,
    borderColor: c.border,
  },
  harvestSummaryTitle: {
    color: c.text,
  },
  harvestSummaryKg: {
    color: c.link,
  },
  harvestAreaCaption: {
    marginTop: 6,
    color: c.textSecondary,
  },
  harvestRowCard: {
    borderRadius: 18,
    backgroundColor: c.backgroundSecondary,
    borderColor: c.border,
    paddingVertical: 16,
  },
  harvestKgText: {
    color: c.text,
  },
  harvestDateText: {
    color: c.textMuted,
  },
  harvestCoopText: {
    color: c.textMuted,
  },
  voucherCard: {
    borderRadius: 22,
    backgroundColor: c.backgroundSecondary,
    borderColor: c.border,
    alignItems: 'center',
    paddingTop: 18,
    paddingBottom: 20,
  },
  voucherShareCapture: {
    width: '100%',
    alignItems: 'center',
    backgroundColor: c.backgroundSecondary,
  },
  voucherQrWrap: {
    width: 192,
    height: 192,
    borderRadius: 18,
    backgroundColor: c.storageTrack,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
    overflow: 'hidden',
  },
  voucherQrInner: {
    backgroundColor: c.backgroundCard,
    padding: 6,
    borderRadius: 12,
    overflow: 'hidden',
  },
  voucherTitle: {
    color: c.text,
  },
  voucherSubtitle: {
    color: c.textMuted,
    marginTop: 2,
  },
  voucherCodeWrap: {
    marginTop: 12,
    width: '100%',
    borderRadius: 12,
    backgroundColor: c.surfaceAccent,
    paddingVertical: 10,
    alignItems: 'center',
  },
  voucherCodeText: {
    color: c.link,
  },
  voucherBodyText: {
    marginTop: 14,
    color: c.textSecondary,
    lineHeight: 30,
  },
  rowCard: { padding: 12 },
  rowHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
  },
  plotTitleBlock: {
    flex: 1,
    minWidth: 0,
    paddingRight: 4,
  },
  plotTitleFull: {
    color: c.text,
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '600',
  },
  plotHectaresLine: {
    marginTop: 4,
    maxWidth: '100%',
    fontSize: 13,
    lineHeight: 18,
    color: c.text,
  },
  plotStatusBadgeRow: {
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  plotRegisteredLine: {
    marginTop: 8,
    color: c.textMuted,
  },
  nextStepBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 14,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: c.surfaceAccentBorder,
    backgroundColor: c.surfaceAccent,
    marginBottom: 4,
  },
  nextStepBannerPressed: {
    opacity: 0.92,
  },
  nextStepIconWrap: {
    width: 36,
    alignItems: 'center',
  },
  nextStepEyebrow: {
    color: c.link,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    fontSize: 11,
  },
  nextStepTitle: {
    marginTop: 2,
    color: c.linkStrong,
    fontSize: 16,
  },
  nextStepHint: {
    marginTop: 4,
    color: c.link,
    lineHeight: 18,
  },
  nextStepCta: {
    color: c.link,
    fontWeight: '700',
    maxWidth: 72,
    textAlign: 'right',
  },
  plotRenameBtn: {
    padding: 5,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: c.surfaceAccentBorder,
    backgroundColor: c.surfaceAccent,
    marginTop: 2,
    flexShrink: 0,
  },
  plotMapHeroPress: {
    marginBottom: 14,
  },
  plotMapCaption: {
    marginTop: 8,
    color: c.link,
    textAlign: 'center',
    fontWeight: '600',
  },
  renameModalKeyboardRoot: {
    flex: 1,
  },
  renameModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingVertical: 16,
  },
  renameModalScrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingVertical: 8,
  },
  renameModalCard: {
    backgroundColor: c.backgroundCard,
    borderRadius: 18,
    padding: 18,
    maxWidth: 400,
    width: '100%',
    alignSelf: 'center',
  },
  renameModalActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 16,
  },
  photoRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 10 },
  photoThumb: { width: 72, height: 72, borderRadius: 12, backgroundColor: c.storageTrack },
  photoThumbMore: {
    width: 72,
    height: 72,
    borderRadius: 12,
    backgroundColor: c.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  deletePlotSection: {
    marginTop: 8,
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: c.border,
    gap: 10,
  },
  deletePlotSectionNote: {
    color: c.textMuted,
    textAlign: 'center',
    lineHeight: 18,
  },
  deletePlotButton: {
    marginTop: 4,
  },
});
}
