import { StyleSheet } from 'react-native';

import type { AppColors } from '@/features/theme/useThemedStyles';

export function createHarvestScreenStyles(c: AppColors) {
  return StyleSheet.create({
    screen: { flex: 1 },
    container: { padding: 16, paddingBottom: 32, gap: 16 },
    header: {
      paddingHorizontal: 16,
      paddingBottom: 6,
    },
    headerRowCompact: {
      position: 'relative',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      minHeight: 42,
      paddingTop: 6,
      paddingBottom: 4,
    },
    headerSideSlot: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
    },
    headerSideLeft: {
      justifyContent: 'flex-start',
    },
    headerSideRight: {
      justifyContent: 'flex-end',
    },
    headerTitleWrap: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 88,
    },
    backButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      minWidth: 78,
    },
    headerTitleCompact: {
      color: '#FFFFFF',
      fontSize: 18,
      lineHeight: 24,
      textAlign: 'center',
      maxWidth: '100%',
    },
    langPillCompact: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingHorizontal: 8,
      paddingVertical: 5,
      borderRadius: 9999,
      backgroundColor: 'rgba(255,255,255,0.16)',
      minWidth: 54,
      justifyContent: 'center',
    },
    langDot: {
      width: 8,
      height: 8,
      borderRadius: 999,
      backgroundColor: '#9FE6C9',
    },
    selectPlotTitle: {
      color: c.text,
      fontSize: 16,
      lineHeight: 22,
      marginBottom: 8,
    },
    plotLocalBadge: {
      color: c.textWarningStrong,
      marginTop: 4,
    },
    selectPlotCard: {
      borderRadius: 20,
      paddingVertical: 16,
      paddingHorizontal: 14,
      borderColor: c.border,
      backgroundColor: c.backgroundCard,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    selectPlotCardSelected: {
      borderColor: c.link,
      borderWidth: 1.5,
      backgroundColor: c.surfaceAccent,
    },
    plotIconWrap: {
      width: 56,
      height: 56,
      borderRadius: 16,
      backgroundColor: c.avatarBackground,
      alignItems: 'center',
      justifyContent: 'center',
    },
    plotSeasonText: {
      color: c.textMuted,
      marginTop: 2,
    },
    weightPlotChip: {
      flexDirection: 'row',
      alignItems: 'center',
      alignSelf: 'flex-start',
      gap: 6,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 999,
      backgroundColor: c.surfaceAccent,
      marginBottom: 4,
    },
    weightPlotChipText: {
      color: c.linkStrong,
      fontSize: 14,
    },
    weightCard: {
      borderRadius: 18,
      borderColor: c.border,
      backgroundColor: c.backgroundCard,
      padding: 16,
      gap: 6,
    },
    weightLabel: {
      color: c.text,
      fontWeight: '600',
      textTransform: 'uppercase',
      letterSpacing: 0.4,
      fontSize: 11,
    },
    weightHint: {
      color: c.textMuted,
      marginBottom: 4,
    },
    weightInputRow: {
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: c.inputBorder,
      borderRadius: 14,
      backgroundColor: c.inputBackground,
      paddingHorizontal: 14,
      paddingVertical: 10,
      gap: 8,
    },
    weightInput: {
      flex: 1,
      textAlign: 'right',
      fontSize: 28,
      lineHeight: 34,
      fontWeight: '700',
      color: c.text,
      paddingVertical: 0,
    },
    weightUnit: {
      color: c.textMuted,
      fontSize: 16,
      minWidth: 24,
    },
    stepperRow: {
      marginTop: 8,
      flexDirection: 'row',
      justifyContent: 'flex-end',
      gap: 8,
    },
    stepperBtn: {
      width: 32,
      height: 32,
      borderRadius: 999,
      backgroundColor: c.backgroundSecondary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    stepperBtnWide: {
      minWidth: 44,
      height: 32,
      paddingHorizontal: 10,
      borderRadius: 999,
      backgroundColor: c.backgroundSecondary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    stepperBtnText: {
      color: c.textSecondary,
      fontWeight: '600',
    },
    disabledRecordBtn: {
      backgroundColor: c.buttonDisabled,
    },
    btnTextOnGreen: {
      color: '#FFFFFF',
    },
    btnTextOnGray: {
      color: c.text,
    },
    btnTextDisabled: {
      color: c.textMuted,
    },
    signInHarvestCard: {
      borderRadius: 18,
      borderColor: c.surfaceAccentBorder,
      backgroundColor: c.surfaceAccent,
      padding: 16,
      alignItems: 'center',
      gap: 8,
    },
    signInHarvestIconWrap: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: c.avatarBackground,
      alignItems: 'center',
      justifyContent: 'center',
    },
    signInHarvestTitle: {
      color: c.helpTitle,
      textAlign: 'center',
    },
    signInHarvestBody: {
      color: c.textMuted,
      textAlign: 'center',
      lineHeight: 20,
      marginBottom: 4,
    },
    selectPlotCardDisabled: {
      opacity: 0.72,
      backgroundColor: c.backgroundSecondary,
    },
    card: { marginTop: 2 },
    introCard: {
      borderRadius: 18,
      borderColor: c.surfaceAccentBorder,
      backgroundColor: c.surfaceAccent,
      gap: 14,
    },
    introActions: {
      gap: 10,
      marginTop: 4,
    },
    multiPlotLinkRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 4,
      paddingVertical: 8,
    },
    multiPlotLinkText: {
      color: c.link,
      fontSize: 14,
    },
    sectionHeaderRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
    },
    rowCard: { padding: 12 },
    deliveryCard: { padding: 14, borderRadius: 16 },
    rowHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
    },
    scaleCardTitle: {
      color: c.linkStrong,
    },
    scaleCardBody: {
      color: c.helpText,
      marginTop: 4,
    },
    receiptsPlotBackRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      marginBottom: 10,
      alignSelf: 'flex-start',
      paddingVertical: 4,
    },
    receiptsPlotBackText: {
      color: c.link,
    },
  });
}
