import { StyleSheet } from 'react-native';

import type { AppColors } from '@/features/theme/useThemedStyles';

export function createDeliveryLoggedPanelStyles(c: AppColors) {
  return StyleSheet.create({
    heroWrap: { alignItems: 'center', marginTop: -4, marginBottom: 2 },
    iconWrap: {
      width: 72,
      height: 72,
      borderRadius: 36,
      backgroundColor: c.surfaceAccent,
      alignItems: 'center',
      justifyContent: 'center',
    },
    iconWrapQueued: { backgroundColor: c.surfaceAccentStrong },
    title: {
      textAlign: 'center',
      color: c.text,
      fontSize: 26,
      lineHeight: 32,
    },
    subtitle: {
      textAlign: 'center',
      color: c.textSecondary,
      marginTop: 6,
      marginBottom: 14,
      lineHeight: 22,
      paddingHorizontal: 8,
    },
    receiptCard: {
      borderRadius: 22,
      backgroundColor: c.backgroundSecondary,
      borderColor: c.border,
      alignItems: 'center',
      paddingVertical: 16,
      marginBottom: 16,
    },
    shareCapture: {
      width: '100%',
      alignItems: 'center',
      backgroundColor: c.backgroundSecondary,
      paddingHorizontal: 12,
    },
    receiptDivider: {
      width: '100%',
      height: StyleSheet.hairlineWidth,
      backgroundColor: c.chipBorder,
      marginVertical: 14,
    },
    summaryLabel: {
      color: c.textMuted,
      textTransform: 'uppercase',
      letterSpacing: 0.4,
      textAlign: 'center',
    },
    plotName: { color: c.text, textAlign: 'center' },
    kgText: { color: c.link, marginTop: 2, textAlign: 'center' },
    metaText: { color: c.textMuted, textAlign: 'center' },
    buyerRow: { marginTop: 10, gap: 2, alignItems: 'center' },
    buyerKey: { color: c.textMuted, textAlign: 'center' },
    buyerValue: { color: c.text, textAlign: 'center' },
    seasonText: { marginTop: 8, color: c.textMuted, textAlign: 'center' },
    qrWrap: {
      width: 192,
      height: 192,
      borderRadius: 18,
      backgroundColor: c.storageTrack,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 8,
    },
    qrInner: {
      backgroundColor: c.backgroundCard,
      padding: 6,
      borderRadius: 12,
    },
    qrReadyTitle: { color: c.text, textAlign: 'center' },
    qrReadyHint: {
      color: c.textMuted,
      marginTop: 4,
      marginBottom: 10,
      textAlign: 'center',
      paddingHorizontal: 8,
    },
    codeWrap: {
      marginBottom: 4,
      width: '100%',
      borderRadius: 12,
      backgroundColor: c.surfaceAccent,
      paddingVertical: 10,
      alignItems: 'center',
    },
    codeText: { color: c.link },
    qrPendingWrap: {
      width: '100%',
      minHeight: 200,
      borderRadius: 18,
      borderWidth: 1,
      borderStyle: 'dashed',
      borderColor: c.chipBorder,
      backgroundColor: c.backgroundCard,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      paddingHorizontal: 20,
      paddingVertical: 24,
      marginBottom: 4,
    },
    qrPendingIcon: {
      width: 64,
      height: 64,
      borderRadius: 32,
      backgroundColor: c.backgroundSecondary,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 4,
    },
    qrPendingTitle: { color: c.text, textAlign: 'center' },
    qrPendingHint: { color: c.textMuted, textAlign: 'center', lineHeight: 20 },
    actions: { gap: 10 },
    syncFeedbackBanner: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
      borderRadius: 12,
      borderWidth: 1,
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    syncFeedbackSuccess: {
      backgroundColor: c.surfaceAccent,
      borderColor: c.surfaceAccentBorder,
    },
    syncFeedbackError: {
      backgroundColor: c.surfaceWarning,
      borderColor: c.surfaceWarningBorder,
    },
    syncFeedbackInfo: {
      backgroundColor: c.backgroundSecondary,
      borderColor: c.border,
    },
    syncFeedbackText: {
      flex: 1,
      color: c.text,
      lineHeight: 20,
    },
    secondaryBtn: { backgroundColor: c.chipBackgroundActive },
    secondaryBtnText: { color: c.linkStrong },
    linkRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 4,
      paddingVertical: 14,
      marginTop: 4,
    },
    linkText: { color: c.link },
    shareNote: { textAlign: 'center', color: c.textMuted, marginTop: 4 },
  });
}

export function createDeliveryReceiptDetailPanelStyles(c: AppColors) {
  return StyleSheet.create({
    wrap: { gap: 12 },
    backRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      alignSelf: 'flex-start',
      paddingVertical: 4,
    },
    backText: { color: c.link },
    receiptCard: {
      borderRadius: 22,
      backgroundColor: c.backgroundSecondary,
      borderColor: c.border,
      alignItems: 'center',
      paddingVertical: 16,
    },
    shareCapture: {
      width: '100%',
      alignItems: 'center',
      backgroundColor: c.backgroundSecondary,
      paddingHorizontal: 8,
    },
    qrWrap: {
      width: 192,
      height: 192,
      borderRadius: 18,
      backgroundColor: c.storageTrack,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 10,
    },
    qrInner: {
      backgroundColor: c.backgroundCard,
      padding: 6,
      borderRadius: 12,
    },
    qrGeneratingWrap: {
      width: 192,
      minHeight: 192,
      borderRadius: 18,
      backgroundColor: c.storageTrack,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 10,
      paddingHorizontal: 16,
      paddingVertical: 20,
      marginBottom: 10,
    },
    qrGeneratingText: { color: c.textMuted, textAlign: 'center', lineHeight: 18 },
    qrHint: { color: c.textMuted, marginBottom: 8, textAlign: 'center' },
    codeWrap: {
      marginBottom: 4,
      width: '100%',
      borderRadius: 12,
      backgroundColor: c.surfaceAccent,
      paddingVertical: 10,
      alignItems: 'center',
    },
    codeText: { color: c.link },
    divider: {
      width: '100%',
      height: StyleSheet.hairlineWidth,
      backgroundColor: c.chipBorder,
      marginVertical: 14,
    },
    summaryLabel: {
      color: c.textMuted,
      textTransform: 'uppercase',
      letterSpacing: 0.4,
      textAlign: 'center',
    },
    plotName: { color: c.text, textAlign: 'center' },
    kgText: { color: c.link, marginTop: 2, textAlign: 'center' },
    metaText: { color: c.textMuted, textAlign: 'center' },
    buyerRow: { marginTop: 10, gap: 2, alignItems: 'center' },
    buyerKey: { color: c.textMuted, textAlign: 'center' },
    buyerValue: { color: c.text, textAlign: 'center' },
    noQr: { color: c.textMuted, textAlign: 'center' },
  });
}

export function createDeliveryReceiptsBrowserStyles(c: AppColors) {
  return StyleSheet.create({
    wrap: { gap: 8 },
    card: { padding: 14 },
    list: { gap: 10 },
    plotHeading: { color: c.text, fontSize: 18 },
    plotSubheading: { color: c.textMuted, marginBottom: 4 },
    tableCard: {
      padding: 0,
      borderRadius: 16,
      overflow: 'hidden',
    },
    tableHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: c.border,
      backgroundColor: c.backgroundSecondary,
    },
    tableHeaderCell: {
      color: c.textMuted,
      textTransform: 'uppercase',
      letterSpacing: 0.35,
      fontSize: 11,
    },
    tableHeaderCellRight: {
      textAlign: 'right',
    },
    tableRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 14,
      paddingVertical: 12,
      backgroundColor: c.backgroundCard,
    },
    tableRowBorder: {
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: c.border,
    },
    tableRowPressed: {
      backgroundColor: c.backgroundSecondary,
    },
    tableColPlot: {
      width: 96,
      maxWidth: '32%',
      flexShrink: 1,
      minWidth: 0,
      paddingRight: 8,
    },
    tableColWeight: {
      width: 78,
      flexShrink: 0,
      alignItems: 'flex-end',
      paddingRight: 16,
    },
    tableColWeightWide: {
      width: 86,
      flexShrink: 0,
      alignItems: 'flex-end',
      paddingRight: 16,
    },
    tableColRecipient: {
      flex: 1,
      flexShrink: 1,
      minWidth: 0,
    },
    tableColChevron: {
      width: 20,
      flexShrink: 0,
      alignItems: 'center',
      marginLeft: 4,
    },
    tablePlotName: {
      color: c.text,
    },
    tableKg: {
      color: c.link,
      textAlign: 'right',
      fontVariant: ['tabular-nums'],
    },
    tableDate: {
      color: c.textMuted,
      marginTop: 2,
      fontVariant: ['tabular-nums'],
      fontSize: 12,
      letterSpacing: -0.2,
    },
    tableDateRight: {
      textAlign: 'right',
    },
    recipientRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 4,
    },
    recipientDefault: { color: c.textSecondary, flex: 1 },
    recipientQr: { color: c.link, flex: 1 },
    recipientPending: { color: c.textWarningStrong, flex: 1 },
    recipientMuted: { color: c.textMuted, flex: 1 },
    chevron: { color: c.textMuted },
  });
}

export function harvestStatusColor(
  c: AppColors,
  variant: 'success' | 'warning' | 'info' | 'error',
): string {
  if (variant === 'success') return c.link;
  if (variant === 'warning' || variant === 'error') return c.textWarningStrong;
  return c.tint;
}
